# Generated by Django 4.2.23 on 2025-07-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='deanery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='education_level',
            field=models.CharField(blank=True, choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('UNDERGRAD', 'Undergraduate'), ('MASTERS', 'Masters'), ('POSTGRAD', 'Post-Graduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('SELF_EMPLOYED', 'Self Employed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
