# Generated by Django 4.2.23 on 2025-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_parishioner_deanery_parishioner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishioner',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('E', 'Separated')], max_length=1),
        ),
    ]
