# Generated by Django 4.2.23 on 2025-07-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_parishioner_marital_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parishioner',
            old_name='date_of_death',
            new_name='death_verification_date',
        ),
        migrations.RenameField(
            model_name='parishioner',
            old_name='deceased',
            new_name='death_verified',
        ),
        migrations.RenameField(
            model_name='parishioner',
            old_name='marriage_date',
            new_name='marriage_verification_date',
        ),
        migrations.RenameField(
            model_name='parishioner',
            old_name='death_details',
            new_name='marriage_verification_notes',
        ),
        migrations.RemoveField(
            model_name='parishioner',
            name='marriage_details',
        ),
        migrations.AddField(
            model_name='parishioner',
            name='death_verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='marriage_verified',
            field=models.BooleanField(default=False),
        ),
    ]
