# Generated by Django 4.2.23 on 2025-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_parishioner_date_of_death_parishioner_death_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishioner',
            name='deanery',
            field=models.CharField(blank=True, choices=[('Agbani Deanery', 'Agbani Deanery'), ('Aguobu Owa Deanery', 'Aguobu Owa Deanery'), ('Emene Deanery', 'Emene Deanery'), ('Enugu Deanery', 'Enugu Deanery'), ('Nkwo Nike Deanery', 'Nkwo Nike Deanery'), ('Udi Deanery', 'Udi Deanery')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
