# Generated by Django 4.2.23 on 2025-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_user_subadminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='parishioner',
            name='single_status_details',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SubAdminProfile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
