# Generated by Django 4.2.23 on 2025-07-07 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0010_baptism_parishioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_numbers', models.TextField(help_text='Comma-separated approved numbers')),
                ('deanery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.deanery')),
            ],
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.parish')),
            ],
        ),
        migrations.CreateModel(
            name='ParishAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.parish')),
                ('priest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.priest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
