# Generated by Django 4.2.23 on 2025-07-07 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_deanery_parish_priest_parishadministrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishadministrator',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='priest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parishadministrator',
            name='priest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registry.priest'),
            preserve_default=False,
        ),
    ]
