# Generated by Django 4.2.23 on 2025-07-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0012_parishadministrator_created_at_priest_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deanery",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="parish",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="parish",
            name="phone_numbers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
