# Generated by Django 4.2.23 on 2025-07-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0013_alter_deanery_name_alter_parish_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parishioner",
            name="lga_of_origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parishioner",
            name="state_of_origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
