# Generated by Django 4.2.23 on 2025-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0014_parishioner_lga_of_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parishioner",
            name="hometown",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
