# Generated by Django 4.2.23 on 2025-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_birthrecord_delete_baptism'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthrecord',
            name='father_unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='mother_unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
