# Generated by Django 4.2.23 on 2025-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0015_parishioner_hometown"),
    ]

    operations = [
        migrations.AddField(
            model_name="parishioner",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parishioner",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
