# Generated by Django 4.2.23 on 2025-07-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_birthrecord_father_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthrecord',
            name='father_lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='father_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='father_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='mother_lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='mother_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='mother_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
