# Generated by Django 4.2.23 on 2025-07-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_birthrecord_father_lga_birthrecord_father_state_and_more'),
        ('registry', '0016_parishioner_latitude_parishioner_longitude'),
    ]

    operations = [
    ]
