# Generated by Django 4.2.23 on 2025-07-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_merge_20250709_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishioner',
            name='deanery',
            field=models.CharField(blank=True, choices=[('Agbani Deanery', 'Agbani Deanery'), ('Aguobu Owa Deanery', 'Aguobu Owa Deanery'), ('Emene Deanery', 'Emene Deanery'), ('Enugu Deanery', 'Enugu Deanery'), ('Nkwo Nike Deanery', 'Nkwo Nike Deanery'), ('Udi Deanery', 'Udi Deanery'), ('Chaplaincy', 'Chaplaincy')], max_length=100, null=True),
        ),
    ]
