# Generated by Django 4.2.23 on 2025-07-09 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0018_alter_parishioner_deanery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_priests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='priest',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='parish',
            name='phone_numbers',
        ),
        migrations.DeleteModel(
            name='ParishAdministrator',
        ),
        migrations.DeleteModel(
            name='Priest',
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.parish'),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parishadminprofile',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.parish'),
        ),
        migrations.AddField(
            model_name='parishadminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
