# Generated by Django 4.1.13 on 2025-07-09 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0019_parishadminprofile_priestprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='priestprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='priestprofile',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='priestprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parishioner',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='parishioner',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parishioner',
            name='lga_of_origin',
        ),
        migrations.RemoveField(
            model_name='parishioner',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='parishioner',
            name='state_of_origin',
        ),
        migrations.AddField(
            model_name='parish',
            name='phone_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='deanery',
            field=models.CharField(blank=True, choices=[('Agbani Deanery', 'Agbani Deanery'), ('Aguobu Owa Deanery', 'Aguobu Owa Deanery'), ('Emene Deanery', 'Emene Deanery'), ('Enugu Deanery', 'Enugu Deanery'), ('Nkwo Nike Deanery', 'Nkwo Nike Deanery'), ('Udi Deanery', 'Udi Deanery')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ParishAdminProfile',
        ),
        migrations.DeleteModel(
            name='PriestProfile',
        ),
        migrations.AddField(
            model_name='priest',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.parish'),
        ),
        migrations.AddField(
            model_name='parishadministrator',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.parish'),
        ),
        migrations.AddField(
            model_name='parishadministrator',
            name='priest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.priest'),
        ),
        migrations.AddField(
            model_name='parishadministrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
