# Generated by Django 4.1.13 on 2025-07-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_priestprofile_parishadminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
