# Generated by Django 4.1.13 on 2025-07-09 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0022_parishioner_latitude_parishioner_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priest',
            name='parish',
        ),
        migrations.AlterField(
            model_name='parishadminprofile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='deanery',
            field=models.CharField(blank=True, choices=[('Agbani Deanery', 'Agbani Deanery'), ('Aguobu Owa Deanery', 'Aguobu Owa Deanery'), ('Emene Deanery', 'Emene Deanery'), ('Enugu Deanery', 'Enugu Deanery'), ('Nkwo Nike Deanery', 'Nkwo Nike Deanery'), ('Udi Deanery', 'Udi Deanery'), ('Chaplaincy', 'Chaplaincy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_priests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ParishAdministrator',
        ),
        migrations.DeleteModel(
            name='Priest',
        ),
    ]
