# Generated by Django 5.2.4 on 2025-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_remove_priest_parish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='lga_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
