# Generated by Django 5.2.4 on 2025-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_parishioner_lga_of_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishioner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
