# Generated by Django 5.2.4 on 2025-07-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_alter_parishioner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishioner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
