# Generated by Django 5.2.4 on 2025-07-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0026_alter_parishioner_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parishioner",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
